# Generated by Django 3.2.11 on 2022-01-08 13:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cord', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('temp', models.CharField(blank=True, max_length=200, null=True)),
                ('humidit_validtime', models.CharField(blank=True, max_length=200, null=True)),
                ('humidit_value', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone_c', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_windDirection', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_windSpeed', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_temperatureUnit', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_isDaytime', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_endTime', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_startTime', models.CharField(blank=True, max_length=200, null=True)),
                ('detailedforecastDesc', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WeatherTask',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
