# Generated by Django 3.2.11 on 2022-01-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0002_auto_20220108_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertask',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
